Add CloudFront distribution invalidation code
Add invalidations for CloudFront distribution after update in update-cloudfront job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -145,6 +145,17 @@ jobs:
           command: |
             yum -y install tar gzip
       - run:
+          name: Get OldWorkflowID and save it to https://memstash.io/
+          command: |
+            export OldWorkflowID=$(aws cloudformation list-exports --query "Exports[?Name==\`WorkflowID\`].Value" --no-paginate --output text)
+            echo ${OldWorkflowID}  
+            if [ -n "$OldWorkflowID" ]
+            then
+            curl -H "Content-Type: text/plain" -H "token: ${CIRCLE_WORKFLOW_ID:0:7}" --request PUT --data ${OldWorkflowID}  https://api.memstash.io/values/old_workflowID
+            else 
+            echo "No old infrastructure exists for UdaPeople"
+            fi            
+      - run:
           name: deploy backend infra
           command: |
             aws cloudformation deploy \
@@ -324,7 +335,6 @@ jobs:
           command: |
             apk add --update curl
             apk add --update bash
-            apk add --update jq
             pip install awscli
       - add_ssh_keys:
           fingerprints: ["0a:ab:9c:78:ab:04:4e:29:a7:dc:63:62:36:ad:c8:c4"]
@@ -333,9 +343,18 @@ jobs:
           command: |
             set TERM=xterm
             export OldWorkflowID=$(aws cloudformation list-exports --query "Exports[?Name=='WorkflowID'].Value" --no-paginate --output text)
+            export STACKS=$(aws cloudformation list-stacks --query "StackSummaries[*].StackName" --stack-status-filter CREATE_COMPLETE --no-paginate --output text)
             echo Old Workflow Id: "${OldWorkflowID}"
-            if [ -n "$OldWorkflowID" ]
-            then        
+            echo Stacks: "${STACKS}"
+            if ! aws cloudformation describe-stacks --stack-name udapeople-cloudfront ;
+            then
+            echo "Stack doesn't exist"
+            aws cloudformation create-stack  \
+              --stack-name udapeople-cloudfront \
+              --template-body file://./.circleci/files/cloudfront.yml \
+              --parameters ParameterKey=WorkflowID,ParameterValue=${CIRCLE_WORKFLOW_ID:0:7} \
+              --tags 'Key=project,Value=udapeople'            
+            else
             echo "Update existing stack"
             aws cloudformation update-stack  \
               --stack-name udapeople-cloudfront \
@@ -343,21 +362,12 @@ jobs:
               --parameters ParameterKey=WorkflowID,ParameterValue=${CIRCLE_WORKFLOW_ID:0:7} \
               --tags 'Key=project,Value=udapeople'
             echo "CloudFront stack updated"
-            export DISTRIBUTION_ID=$(aws cloudformation describe-stacks --stack-name udapeople-cloudfront | jq -r '.Stacks[0].Outputs[] | select(.OutputKey=="ClientDistribution").OutputValue)
-            echo "Distribution ID: ${DISTRIBUTION_ID}"
-            export INVALIDATION_ID=$(aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*" | jq -r .Invalidation.Id)
-            echo "Invalidation ID: ${INVALIDATION_ID}"
-            aws cloudfront wait invalidation-completed --distribution-id $DISTRIBUTION_ID --id $INVALIDATION_ID
-            echo "CloudFront Invalidation completed"
-            else
-            echo "Stack doesn't exist"
-            aws cloudformation create-stack  \
-              --stack-name udapeople-cloudfront \
-              --template-body file://./.circleci/files/cloudfront.yml \
-              --parameters ParameterKey=WorkflowID,ParameterValue=${CIRCLE_WORKFLOW_ID:0:7} \
-              --tags 'Key=project,Value=udapeople'            
-            fi            
-            if [ -n "$OldWorkflowID" ]
+            echo "Get distribution ID"
+            export $DISTRIBUTION_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Origins.Items[?DomainName=='udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}']].Id" --output text)
+            echo "Create invalidation using Distribution ID"
+            aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
+            fi
+            if ! aws cloudformation describe-stacks --stack-name udapeople-frontend-${OldWorkflowID} ;
             then
               echo "Empty old S3 bucket and delete old frontend stack"
               if aws s3api head-bucket --bucket udapeople-frontend-${OldWorkflowID}
@@ -365,6 +375,9 @@ jobs:
                 aws s3 rm s3://udapeople-frontend-${OldWorkflowID}/ --recursive
               fi
               aws cloudformation delete-stack --stack-name udapeople-frontend-${OldWorkflowID}
+            fi
+            if ! aws cloudformation describe-stacks --stack-name udapeople-backend-${OldWorkflowID} ;
+            then
               echo "Delete old backend stack"
               aws cloudformation delete-stack --stack-name udapeople-backend-${OldWorkflowID}
             fi
